### ISSUE TITLE
Data should be merged?

### ISSUE THREAD

**Issue by m4ce** [ripienaar/puppet-classifier#8]
Hi,

take the following example into consideration.

A machine has the following defined at the ENC level:

```
roles:
  - "custom1"
  - "custom2"
```

The classifier looks as follows:

```
  "Role: custom1":
    rules:
      - fact: "%{::roles}"
        operator: in
        value: "custom1"
    data:
      a::opts:
        var1: 1
  "Role: custom2":
    rules:
      - fact: "%{::roles}"
        operator: in
        value: "custom2"
    data:
      a::opts:
        var2: 1
```

I would expect the data to be merged when a node matches multiple rules. What do you think? I guess it should probably observe the lookup_options for that specific key?
